name: Docker build

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: |
          docker build ./alpine3.16/fpm
          docker build bullseye/apache
          docker build bullseye/fpm
